Use source-inplace instead of source when defining checker
If the clang-tidy command is running via ssh, with 'source, flycheck
will generate the temp file on the local host, so the remote
clang-tidy process will fail, error like:

Error reading configuration from /.../tmp/flycheckzWPEWe: directory doesn't exist.
error: no input files [clang-diagnostic-error]
error: no such file or directory: '/.../tmp/flycheckzWPEWe/foo.cpp' [clang-diagnostic-error]